## Bert Model & Bert Tokenizer 

* bert-base-multilinual-cases 

### Tokenizer

In [1]:
from transformers import TFBertTokenizer,BertTokenizer,TFBertModel

/Users/ijeonghun/Documents/github/Lunch_lab/LLM/Bert/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


아래와 같이 vocab.text 를 가져와 차후 업데이트해야함

다양한 음식명 등은 학습되지않았으므로

In [2]:
vacab_path="https://huggingface.co/bert-base-multilingual-cased/resolve/main/vocab.txt"
import requests
rq_vacab=requests.get(vacab_path)
vocab=rq_vacab.text if rq_vacab.status_code==200 else None
with open("vocab.text","w") as f:
    f.write(vocab)

In [3]:
bert_base_tokenizer=BertTokenizer.from_pretrained("bert-base-multilingual-cased",clean_up_tokenization_spaces=True)
base_setting=bert_base_tokenizer.init_kwargs.copy()
Own_tokenizer=BertTokenizer(vocab_file="vocab.text",**base_setting)

In [4]:
base_setting

{'do_lower_case': False,
 'do_basic_tokenize': True,
 'never_split': None,
 'unk_token': '[UNK]',
 'sep_token': '[SEP]',
 'pad_token': '[PAD]',
 'cls_token': '[CLS]',
 'mask_token': '[MASK]',
 'tokenize_chinese_chars': True,
 'strip_accents': None,
 'clean_up_tokenization_spaces': True,
 'model_max_length': 512,
 'tokenizer_file': '/Users/ijeonghun/.cache/huggingface/hub/models--bert-base-multilingual-cased/snapshots/3f076fdb1ab68d5b2880cb87a0886f315b8146f8/tokenizer.json',
 'name_or_path': 'bert-base-multilingual-cased'}

In [5]:
Own_tokenizer.tokenize("안녕하세요. 테스트용입니다")

['안', '##녕', '##하', '##세', '##요', '.', '테', '##스트', '##용', '##입', '##니다']

파라미터 설명

padding=True : 필요한 경우에만 패딩처리

padding=max_langth : 최대 길이로 패딩처리

trunaction=True : 일정 길이 이상의 문장을 잘라버림

In [6]:
print(Own_tokenizer.encode("안녕하세요. 테스트용입니다",truncation=True,padding="max_length"))

[101, 9521, 118741, 35506, 24982, 48549, 119, 9866, 34994, 24974, 58303, 48345, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

위에서 보다시피 BertModel은 최대 시퀀스 길이를 512로 제한하고 있습니다

### Model

Tensorflow 모델은 아래 TFBertModel 을 사용해야합니다

In [7]:
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')
model = TFBertModel.from_pretrained("bert-base-multilingual-cased")
text = "Replace me by any text you'd like."
encoded_input = Own_tokenizer(text, return_tensors='tf')
output = model(encoded_input)

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

잘 작동했다면 오케이

In [8]:
output

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(1, 13, 768), dtype=float32, numpy=
array([[[ 0.25244173, -0.5320835 ,  0.44963565, ...,  1.1428412 ,
         -0.6238021 , -0.07453363],
        [ 0.53735644,  0.07007825,  0.48796463, ...,  1.080039  ,
         -0.5559516 , -0.55644274],
        [ 0.46855763, -0.32863384,  0.47817138, ...,  1.1656264 ,
         -0.738888  , -0.392017  ],
        ...,
        [ 0.48219374, -1.082198  ,  0.90263814, ...,  1.8029271 ,
         -1.1342973 , -0.10343555],
        [ 0.12828042, -0.65504766,  0.37227008, ...,  0.78174776,
         -0.9172803 , -0.04007212],
        [ 0.16448611, -0.52388227,  0.66378236, ...,  0.7964226 ,
         -0.73260623, -0.26415116]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[ 0.3479021 , -0.04663813,  0.45640564, -0.24642836, -0.05631405,
         0.5865305 ,  0.4806916 ,  0.24746308, -0.5662966 ,  0.42599705,
         0.01355288, -0.335

## Comment_data

In [9]:
from pandas import read_excel,read_csv
from sklearn import pipeline as pip
from sklearn import preprocessing as pre
from sklearn import model_selection as mod
data=read_excel("../Data/맞춤법검사완료.xlsx",index_col=0)

리뷰 최대 길이를 확인해보자

In [10]:
data

place_review  감성  \
0      천원 별로 사진에 벌집이 있어서 시켰는데 벌집없이 나옴 키오스크사진 다시보니까 사진...  부정   
1                   제대로 안 읽은 내 잘못도 분명 있지만 사진에 저렇게 왜 해둔건지  부정   
2                   이게 현지맛인지 모르겠지만 명 같이 갔는데 다 간이 쎄다고 했어요  부정   
3                                       새우는 통통하니 아주 좋았어요  긍정   
4                                                정식 맛있어요  긍정   
...                                                  ...  ..   
14368                가족들이랑 갔는데 인분이라고 하기에는 턱없이 적은 고기양이었어요  부정   
14369  야채만 가득있는 느낌이랄까 인이라고 말했는데도 그릇과 컵 전부 인만 준비해주고 더 ...  부정   
14370  뭐든지 맥주를 시켜도 까먹으셔서 다른분한테 또 주문 추가로 음료를 시켜도 감감무소식...  부정   
14371                                       넘 짜증나서 리뷰씁니다  부정   
14372                                       역시 하이디라오 존맛탱  긍정   

                                        Spelling_checked  
0      천원 별로 사진에 벌집이 있어서 시켰는데 벌집 없이 나옴 키오스크 사진 다시 보니까...  
1                  제대로 안 읽은 내 잘못도 분명 있지만 사진에 저렇게 왜 해둔 건지  
2                  이게 현지 맛인지 모르겠지만 명 같이 갔는데 다 간이 세다고 했어요  
3                                       새우는 통통하니 아주 좋았어요  
4                                                정식 맛있어요  
...                                                  ...  
14368               가족들이랑 갔는데 인분이라고 하기에는 턱없이 적은 고기 양이었어요  
14369  야채만 가득 있는 느낌이랄까 인이라고 말했는데도 그릇과 컵 전부 인만 준비해 주고 ...  
14370  뭐든지 맥주를 시켜도 까먹으셔서 다른 분한테 또 주문 추가로 음료를 시켜도 감감무소...  
14371                                    너무 짜증 나서 리뷰 씁니다  
14372                                       역시 하이디라오 존맛탱  

[14373 rows x 3 columns]

In [11]:
print(data.place_review.map(lambda x:len(x)).max())
print(data.Spelling_checked.map(lambda x:len(x)).max())

348
357


위와 같이 길이는 문제가 없습니다

In [12]:
Own_tokenizer.tokenize("국수")

['국', '##수']

위와 같이 음식 고유명사에 대한 vocab.txt 갱신이 필요할 수 있음

## 데이터 처리

In [13]:
data["감성"]=data.감성.map(lambda x:1 if x=="긍정" else 0)

5차 5겹

In [14]:
data.감성.value_counts()

감성
1    12509
0     1864
Name: count, dtype: int64

위와 같이 데이터 불균형이 굉장히 심함.

따라서 다음과 같이 처리하겠습니다.

1. 5X5 Kfold with stratified

2. undersampling

In [15]:
from imblearn.under_sampling import RandomUnderSampler
from tqdm import tqdm
kfolds=mod.RepeatedStratifiedKFold(n_repeats=5,n_splits=5,random_state=1)
undersampling=RandomUnderSampler(random_state=1)

In [16]:
data_dc={}
for i,(train,test) in enumerate(kfolds.split(X=data.Spelling_checked,y=data.감성)):
    sub_train=data.loc[train]
    sub_test=data.loc[test]

    # 훈련시 불균형 해소를 위해
    sampling_train=undersampling.fit_resample(X=sub_train["Spelling_checked"].to_frame(),y=sub_train["감성"].to_frame())
    data_dc[i]=(sampling_train,sub_test)

위를 기본으로 BertModel에 맞게 바꾸어야함

In [17]:
from pandas import DataFrame,merge
def trans_data_for_bert(X:DataFrame,tokenizer=Own_tokenizer):
      feature_col="Spelling_checked"
      label_col="감성"

      trans_fuction=lambda sentence:tokenizer.encode_plus(sentence,truncation=True,padding="max_length")
      #trans=X[feature_col].map(trans_fuction)
      trans=[]
      for i in tqdm(X.index):
            trans.append(trans_fuction(X.loc[i,feature_col]))

      temp_={key:[value[key] for value in trans] for key in ['input_ids', 'token_type_ids', 'attention_mask']}
      return temp_,X[label_col].values.tolist()

In [18]:
test_trans=trans_data_for_bert(data.loc[:4])

100%|██████████| 5/5 [00:00<00:00, 2119.41it/s]


In [19]:
print(test_trans[0])

{'input_ids': [[101, 9746, 14279, 9353, 11261, 9405, 18623, 10530, 9339, 38696, 10739, 90587, 9485, 119305, 41850, 9339, 38696, 73610, 8982, 119156, 9838, 28188, 12605, 20308, 9405, 18623, 25805, 9356, 25503, 118671, 9405, 18623, 86933, 9339, 38696, 9960, 16323, 11664, 9429, 16758, 15303, 9339, 38696, 8964, 9448, 12605, 96279, 48549, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [20]:
kfold_list={"train":[],"test":[]}
for i,(train,test) in enumerate(kfolds.split(X=data.Spelling_checked,y=data.감성)):
    sub_train=data.loc[train]
    sub_test=data.loc[test]

    #훈련시 불균형 해소를 위해
    sampling_train=undersampling.fit_resample(X=sub_train["Spelling_checked"].to_frame(),y=sub_train["감성"].to_frame())
    kfold_list["train"].append(trans_data_for_bert(merge(*sampling_train,left_index=True,right_index=True)))

    kfold_list["test"].append(trans_data_for_bert(sub_test))

100%|██████████| 2874/2874 [00:00<00:00, 6448.25it/s]


In [21]:
len(kfold_list["train"])

25

In [22]:
print(Own_tokenizer.encode_plus("테스트용 문장입니다",truncation=True,padding="max_length").keys())
print(len(Own_tokenizer.encode_plus("테스트용 문장입니다",truncation=True,padding="max_length")["input_ids"]))

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])
512


In [23]:
from tensorflow import keras
from tensorflow import int32

input_ids=keras.layers.Input(shape=(512,),dtype=int32,name="input_ids")
attention_mask=keras.layers.Input(shape=(512,),dtype=int32,name="attention_mask")
token_type_id=keras.layers.Input(shape=(512,),dtype=int32,name="token_type_id")
bert_output=model([input_ids,attention_mask,token_type_id])

In [24]:
#우리는 아래의 pooler_output 을 사용해야합니다
bert_output.pooler_output

<KerasTensor: shape=(None, 768) dtype=float32 (created by layer 'tf_bert_model')>

In [25]:
sentiment_layer=keras.layers.Dense(1, activation='sigmoid', kernel_initializer=keras.initializers.TruncatedNormal(stddev=0.02))(bert_output.pooler_output)
sentiment_model=keras.Model([input_ids,attention_mask,token_type_id],sentiment_layer)

In [26]:
sentiment_model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_ids (InputLayer)      [(None, 512)]                0         []                            
                                                                                                  
 attention_mask (InputLayer  [(None, 512)]                0         []                            
 )                                                                                                
                                                                                                  
 token_type_id (InputLayer)  [(None, 512)]                0         []                            
                                                                                                  
 tf_bert_model (TFBertModel  TFBaseModelOutputWithPooli   1778534   ['input_ids[0][0]',       

잘 만들어졌네요

In [27]:
# TPU = True
# if TPU:
#   resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='grpc://' + os.environ['COLAB_TPU_ADDR'])
#   tf.config.experimental_connect_to_cluster(resolver)
#   tf.tpu.experimental.initialize_tpu_system(resolver)
# else:
#   pass

transformer model 에 추천되는 optimizer 설치

버전 에러가 일어남

In [28]:
#!pip install tensorflow_addons
#learning_rate=1e-6,weight_decay=0.0025, warmup_proportion=0.05

In [29]:
# Optimizer=keras.optimizers.AdamW(learning_rate=1e-6,weight_decay=0.0025) #로컬환경에서 느림

In [30]:
early_stopping=keras.callbacks.EarlyStopping(monitor="val_accuracy",patience=5,restore_best_weights=True)
check_point=keras.callbacks.ModelCheckpoint(filepath=".",save_best_only=True,monitor="val_accuracy",mode="min")

callback=[early_stopping,check_point]

In [31]:
Optimizer=keras.optimizers.legacy.Adam(learning_rate=1e-6)
loss=keras.losses.BinaryCrossentropy()

sentiment_model.compile(optimizer=Optimizer,loss=loss,metrics=["accuracy","f1_score","recall","precision"])

In [32]:
kfold_list.keys()

dict_keys(['train', 'test'])

In [ ]:
history=sentiment_model.fit(kfold_list["train"],epochs=100,shuffle=True,validation_data=kfold_list["test"],callbacks=callback,batch_size=100,verbose=1)